## Arrays

#### 1. Array

In [1]:
import array

Creation

In [2]:
arr1 = array.array('i', [10, 20, 30, 40, 50])
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [3]:
arr2 = array.array('i', [60, 70, 80, 90, 100])
print(arr2)

array('i', [60, 70, 80, 90, 100])


access

In [4]:
arr1[2]

30

In [5]:
arr1[3]

40

traversal

In [6]:
for element in arr1:
    print(element, end=' ')

10 20 30 40 50 

insertion

In [7]:
arr1.insert(3, 35)

In [8]:
print(arr1)

array('i', [10, 20, 30, 35, 40, 50])


deletion

In [9]:
arr1.remove(30)

In [10]:
print(arr1)

array('i', [10, 20, 35, 40, 50])


updation

In [11]:
arr1[2] = 30
print(arr1)

array('i', [10, 20, 30, 40, 50])


sorting

In [12]:
arr3 = array.array('i', [4, 7, 3, 9, 2, 6])
print(arr3)

array('i', [4, 7, 3, 9, 2, 6])


In [13]:
sorted_arr3 = array.array('i', sorted(arr3))
print(sorted_arr3)

array('i', [2, 3, 4, 6, 7, 9])


merging

In [14]:
arr1

array('i', [10, 20, 30, 40, 50])

In [15]:
arr2

array('i', [60, 70, 80, 90, 100])

In [16]:
arr3

array('i', [4, 7, 3, 9, 2, 6])

In [17]:
arr4 = arr1 + arr2
print(arr4)

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90, 100])


splitting

In [18]:
ix = int(len(arr4)/2)
ix

5

In [19]:
arr4[:ix]

array('i', [10, 20, 30, 40, 50])

In [20]:
arr4[ix:]

array('i', [60, 70, 80, 90, 100])

2.Numpy

In [21]:
import numpy as np

Creation

In [22]:
np1 = np.array([10, 20, 30, 40, 50])
np2 = np.array([50, 60, 70])

print(np1)
print(np2)

[10 20 30 40 50]
[50 60 70]


In [23]:
np1

array([10, 20, 30, 40, 50])

access

In [24]:
int(np1[0])

10

traversal

In [25]:
for ele in np1:
    print(int(ele), end=' ')

10 20 30 40 50 

insertion

In [26]:
np.insert(np1, 3, 35)

array([10, 20, 30, 35, 40, 50])

deletion

In [27]:
np.delete(np1, 3)

array([10, 20, 30, 50])

updation

In [28]:
np1[2] = 35
print(np1)

[10 20 35 40 50]


sorting


In [29]:
np3 = np.array([5, 3, 7, 6, 2, 9])

In [30]:
np.sort(np3)

array([2, 3, 5, 6, 7, 9])

merging

In [31]:
np1

array([10, 20, 35, 40, 50])

In [32]:
np2

array([50, 60, 70])

In [33]:
np3 = np.concatenate((np1, np2))
print(np3)

[10 20 35 40 50 50 60 70]


splitting

In [34]:
split1, split2 = np.array_split(np3, 2)

In [35]:
split1

array([10, 20, 35, 40])

In [36]:
split2

array([50, 50, 60, 70])

vectorization

In [37]:
np1

array([10, 20, 35, 40, 50])

In [38]:
np1 + 10

array([20, 30, 45, 50, 60])

In [39]:
np1 * 2

array([ 20,  40,  70,  80, 100])

In [42]:
np3 = np.array([4, 5])
np4 = np.array([6, 7])

np3 * np4

array([24, 35])

In [43]:
li1 = [4, 5, 6]
li2 = [1, 2, 3]

In [44]:
for i in range(len(li1)):
    print(li1[i] + li2[i])

5
7
9


In [46]:
for i in range(len(li1)):
    print(li1[i] + 10)

14
15
16
